name: Build and Test iOS Project

on:
  push:
    branches:
      - main  # Триггерим процесс на push в ветку main
  pull_request:
    branches:
      - main  # Триггерим процесс при открытии PR на main

jobs:
  build:
    runs-on: macos-latest  # Указываем, что используем MacOS runner для сборки

    steps:
      # Шаг 1: Checkout репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установка Xcode и зависимостей
      - name: Set up Xcode
        uses: macos-actions/setup-xcode@v2
        with:
          xcode-version: '15.2'  # Убедитесь, что используете актуальную версию Xcode

      # Шаг 3: Установка CocoaPods (если используете CocoaPods)
      - name: Install dependencies (CocoaPods)
        run: |
          gem install cocoapods
          pod install

      # Шаг 4: Сборка проекта Xcode
      - name: Build Xcode Project
        run: |
          xcodebuild -project "Fitness Tracker.xcodeproj" \
          -scheme "Fitness Tracker" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          clean build

      # Шаг 5: Тестирование проекта
      - name: Run Unit Tests
        run: |
          xcodebuild test -project "Fitness Tracker.xcodeproj" \
          -scheme "Fitness Tracker" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15'
