name: Build Fitness Tracker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List Xcode versions
      run: ls /Applications | grep Xcode

    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app

    - name: List Xcode versions
      run: ls /Applications | grep Xcode

    - name: Build project
      run: xcodebuild -project "Fitness Tracker.xcodeproj" -scheme "Fitness Tracker" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15' build
