name: Build and Test iOS Project

on:
  push:
    branches:
      - main  # Триггерим процесс на push в ветку main
  pull_request:
    branches:
      - main  # Триггерим процесс при открытии PR на main

jobs:
  test:
    runs-on: macos-latest  # Запускаем на macOS
    steps:
      - name: 📥 Клонируем репозиторий
        uses: actions/checkout@v4

      - name: 🛠️ Устанавливаем Xcode версию
        run: sudo xcode-select -s /Applications/Xcode_15.0.app  # Укажи актуальную версию

      - name: 📦 Устанавливаем зависимости
        run: |
          cd Fitness Tracker  # Укажи путь до проекта, если он в подпапке
          pod install --silent || echo "No CocoaPods"

      - name: 🔍 Запускаем тесты
        run: |
          cd Fitness Tracker
          xcodebuild test \
            -scheme Fitness Tracker \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
            -enableCodeCoverage YES | xcpretty && exit ${PIPESTATUS[0]}

      - name: 📊 Загружаем покрытие кода (опционально)
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
