name: Build and Test iOS Project

on:
  push:
    branches:
      - main  # Триггерим процесс на push в ветку main
  pull_request:
    branches:
      - main  # Триггерим процесс при открытии PR на main

jobs:
  build:
    runs-on: macos-latest  # Указываем, что используем MacOS runner для сборки

    steps:
      # Шаг 1: Checkout репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 3: Сборка проекта Xcode
      - name: Build Xcode Project
        run: |
          xcodebuild -project "Fitness Tracker.xcodeproj" \
          -scheme "Fitness Tracker" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          clean build

      # Шаг 4: Тестирование проекта
      - name: Run Unit Tests
        run: |
          xcodebuild test -project "Fitness Tracker.xcodeproj" \
          -scheme "Fitness Tracker" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15'
